env: DEV
spring:
  application:
    name: gateway
  security:
    user:
      name: admin
      password: admin
  cloud:
    gateway:
      routes:
        - id: sab-exceed-services
          uri: lb://sab-exceed-services
          predicates:
            - Path=/user/**
          filters:
            - name: AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: sab-exceed-services
                fallbackUri: forward:/serviceUnavailableFallback
    discovery:
      enabled: true

server:
  port: 9000

eureka:
  client:
    register-with-eureka: false
    #service-url:
    #  defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      sab-exceed-services:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000ms # 10 seconds before trying again
        permittedNumberOfCallsInHalfOpenState: 3

logging:
  file:
    name: logs/gateway.log
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.security: DEBUG
    com.sabtok.gateway: DEBUG
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: 'health,circuitbreakers,circuitbreakerevents'
  endpoint:
    health:
      show-details: always # Vital to see individual breaker statuses