spring.application.name=config-server
server.port=8888
# Use 'file:///' prefix for local paths. Windows may need an extra /
spring.cloud.config.server.git.uri=https://github.com/Karbasappa/config-file-repository.git
spring.cloud.config.server.git.search-paths={application}
spring.cloud.config.server.git.default-label: main
