env: STAGE
server:
  error:
    include-stacktrace: NEVER
  port: 8081
  servlet:
    context-path: /sab-info-services-5
spring:
  application:
    name: sab-info-services
  boot:
    main:
      banner-mode: on
    admin:
      client:
        enable: true
        url: http://sab-dashboard-service:9091
        period: 10s
        instance:
          #name: ${spring.application.name}
          #hostname: localhost
          service-base-url: http://sab-info-services:8081
        #prefer-ip-address: true
        service-host-type: ip
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: update
  main:
    banner-mode: log
  datasource:
    tomcat:
      initialSize: '20'
      max-active: '25'
    password: admin1
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://host.docker.internal:3306/sabwiki_production_01_oct_2023
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
linkage:
  scheduler:
    user:
      story:
        cron: 0 */5 * ? * *
    incident:
      cron: 0 */5 * ? * *
feign:
  client:
    exceed:
      url: http://host.docker.internal:5001
    plm:
      url: http://host.docker.internal:8080/sab-plm-services-2.6
logging:
  path: logs
  file: logs/mylog.log
cross-origin: '*'
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

cache:
  type: redis
  data:
    redis:
      host: host.docker.internal # Change to host.docker.internal if the client is also in Docker
      port: 6379
      connection-timeout: 500ms
      time-to-live: 500ms
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 1
        max-wait: 500ms
      cache-null-values: false
      use-key-prefix: true
      #key-prefix: sab-process-service:
      #lettuce:
      #shutdown-timeout: 200ms

eureka:
  client:
    register-with-eureka: true
    service-url.defaultZone: http://registry:8761/eureka