env: DEV
server:
  port: '8081'
  servlet:
    #context-path: /sabtok
spring:
  application:
    name: sab-management-services
  kafka:
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: localhost:9092
    consumer:
      group-id: group-id
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        allow:
          auto:
            create:
              topics: 'false'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: 'true'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: admin1
    username: root
    url: jdbc:mysql://host.docker.internal:3306/prod-sabtok
management:
  endpoints:
    web:
      exposure:
        include: '*'
plm-url: http://laptop-paulleg2:8080/sab-plm-services-2.6/issue/list
scheduler:
  phase-scheduler:
    cron: 0 0/10 * * * *
  review-request-processor:
    cron: 0 0/10 * * * *
  phase-initiator-risk-calculator:
    cron: 0 0/10 * * * *
  phase-initiator-review:
    cron: 0 0/10 * * * *
tsh:
  threshold:
    value: '68'
logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: TRACE
      apache:
        kafka: 'OFF'
propertyurl: http://localhost:8081/property/list
diabetic:
  threshold:
    value: '68'
fileRootPath: C:\sabtok-file-demo
exceed-url: http://localhost:8082/user/list